# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:17:15+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class AgentDeviceId(BaseModel):
    id: Optional[str] = Field(None, description='Third-party device ID.')


class AgentOtherDeviceId(BaseModel):
    agentId: Optional[str] = Field(
        None, description='Project ID for your smart home Action.'
    )
    deviceId: Optional[str] = Field(None, description='Unique third-party device ID.')


class DeviceInfo(BaseModel):
    hwVersion: Optional[str] = Field(None, description='Device hardware version.')
    manufacturer: Optional[str] = Field(None, description='Device manufacturer.')
    model: Optional[str] = Field(None, description='Device model.')
    swVersion: Optional[str] = Field(None, description='Device software version.')


class DeviceNames(BaseModel):
    defaultNames: Optional[List[str]] = Field(
        None,
        description='List of names provided by the manufacturer rather than the user, such as serial numbers, SKUs, etc.',
    )
    name: Optional[str] = Field(
        None, description='Primary name of the device, generally provided by the user.'
    )
    nicknames: Optional[List[str]] = Field(
        None, description='Additional names provided by the user for the device.'
    )


class Empty(BaseModel):
    pass


class QueryRequestPayload(BaseModel):
    devices: Optional[List[AgentDeviceId]] = Field(
        None, description='Third-party device IDs for which to get the device states.'
    )


class QueryResponsePayload(BaseModel):
    devices: Optional[Dict[str, Dict[str, Any]]] = Field(
        None,
        description='States of the devices. Map of third-party device ID to struct of device states.',
    )


class ReportStateAndNotificationDevice(BaseModel):
    notifications: Optional[Dict[str, Any]] = Field(
        None,
        description='Notifications metadata for devices. See the **Device NOTIFICATIONS** section of the individual trait [reference guides](https://developers.home.google.com/cloud-to-cloud/traits).',
    )
    states: Optional[Dict[str, Any]] = Field(
        None,
        description='States of devices to update. See the **Device STATES** section of the individual trait [reference guides](https://developers.home.google.com/cloud-to-cloud/traits).',
    )


class ReportStateAndNotificationResponse(BaseModel):
    requestId: Optional[str] = Field(
        None, description='Request ID copied from ReportStateAndNotificationRequest.'
    )


class RequestSyncDevicesRequest(BaseModel):
    agentUserId: Optional[str] = Field(
        None, description='Required. Third-party user ID.'
    )
    async_: Optional[bool] = Field(
        None,
        alias='async',
        description='Optional. If set, the request will be added to a queue and a response will be returned immediately. This enables concurrent requests for the given `agent_user_id`, but the caller will not receive any error responses.',
    )


class RequestSyncDevicesResponse(BaseModel):
    pass


class StateAndNotificationPayload(BaseModel):
    devices: Optional[ReportStateAndNotificationDevice] = Field(
        None, description='The devices for updating state and sending notifications.'
    )


class SyncRequest(BaseModel):
    agentUserId: Optional[str] = Field(
        None, description='Required. Third-party user ID.'
    )
    requestId: Optional[str] = Field(None, description='Request ID used for debugging.')


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class Device(BaseModel):
    attributes: Optional[Dict[str, Any]] = Field(
        None, description='Attributes for the traits supported by the device.'
    )
    customData: Optional[Dict[str, Any]] = Field(
        None,
        description='Custom device attributes stored in Home Graph and provided to your smart home Action in each [QUERY](https://developers.home.google.com/cloud-to-cloud/intents/query) and [EXECUTE](https://developers.home.google.com/cloud-to-cloud/intents/execute) intent. Data in this object has a few constraints: No sensitive information, including but not limited to Personally Identifiable Information.',
    )
    deviceInfo: Optional[DeviceInfo] = Field(
        None,
        description='Device manufacturer, model, hardware version, and software version.',
    )
    id: Optional[str] = Field(None, description='Third-party device ID.')
    name: Optional[DeviceNames] = Field(
        None, description='Names given to this device by your smart home Action.'
    )
    notificationSupportedByAgent: Optional[bool] = Field(
        None,
        description='Indicates whether your smart home Action will report notifications to Google for this device via ReportStateAndNotification. If your smart home Action enables users to control device notifications, you should update this field and call RequestSyncDevices.',
    )
    otherDeviceIds: Optional[List[AgentOtherDeviceId]] = Field(
        None,
        description='Alternate IDs associated with this device. This is used to identify cloud synced devices enabled for [local fulfillment](https://developers.home.google.com/local-home/overview).',
    )
    roomHint: Optional[str] = Field(
        None,
        description='Suggested name for the room where this device is installed. Google attempts to use this value during user setup.',
    )
    structureHint: Optional[str] = Field(
        None,
        description='Suggested name for the structure where this device is installed. Google attempts to use this value during user setup.',
    )
    traits: Optional[List[str]] = Field(
        None,
        description='Traits supported by the device. See [device traits](https://developers.home.google.com/cloud-to-cloud/traits).',
    )
    type: Optional[str] = Field(
        None,
        description='Hardware type of the device. See [device types](https://developers.home.google.com/cloud-to-cloud/guides).',
    )
    willReportState: Optional[bool] = Field(
        None,
        description='Indicates whether your smart home Action will report state of this device to Google via ReportStateAndNotification.',
    )


class QueryRequestInput(BaseModel):
    payload: Optional[QueryRequestPayload] = Field(
        None, description='Payload containing third-party device IDs.'
    )


class QueryResponse(BaseModel):
    payload: Optional[QueryResponsePayload] = Field(
        None, description='Device states for the devices given in the request.'
    )
    requestId: Optional[str] = Field(
        None, description='Request ID used for debugging. Copied from the request.'
    )


class ReportStateAndNotificationRequest(BaseModel):
    agentUserId: Optional[str] = Field(
        None, description='Required. Third-party user ID.'
    )
    eventId: Optional[str] = Field(
        None, description='Unique identifier per event (for example, a doorbell press).'
    )
    followUpToken: Optional[str] = Field(None, description='Deprecated.')
    payload: Optional[StateAndNotificationPayload] = Field(
        None,
        description='Required. State of devices to update and notification metadata for devices.',
    )
    requestId: Optional[str] = Field(None, description='Request ID used for debugging.')


class SyncResponsePayload(BaseModel):
    agentUserId: Optional[str] = Field(None, description='Third-party user ID')
    devices: Optional[List[Device]] = Field(
        None, description='Devices associated with the third-party user.'
    )


class QueryRequest(BaseModel):
    agentUserId: Optional[str] = Field(
        None, description='Required. Third-party user ID.'
    )
    inputs: Optional[List[QueryRequestInput]] = Field(
        None,
        description='Required. Inputs containing third-party device IDs for which to get the device states.',
    )
    requestId: Optional[str] = Field(None, description='Request ID used for debugging.')


class SyncResponse(BaseModel):
    payload: Optional[SyncResponsePayload] = Field(
        None, description='Devices associated with the third-party user.'
    )
    requestId: Optional[str] = Field(
        None, description='Request ID used for debugging. Copied from the request.'
    )
